// <auto-generated />
using System;
using IRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRM.Data.Migrations
{
    [DbContext(typeof(IrmDbContext))]
    [Migration("20260921030335_InitialSqlServerV101")]
    partial class InitialSqlServerV101
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRM.Data.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeUnitId");

                    b.ToTable("AccommodationsV010", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Account", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.AdministrativeUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LegacyDistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyWardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("PredecessorId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegacyDistrictId")
                        .HasDatabaseName("IX_AU_LegacyDistrictId");

                    b.HasIndex("LegacyWardId")
                        .HasDatabaseName("IX_AU_LegacyWardId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PredecessorId");

                    b.HasIndex("Code", "ValidFrom")
                        .IsUnique();

                    b.ToTable("AdministrativeUnits", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ArchivedEmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CardCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CareerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfLeave")
                        .HasColumnType("datetime2");

                    b.Property<int>("FamilyVisit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FamilyVisitEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyVisitNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyVisitRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyVisitRelativeIdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyVisitRelativeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FamilyVisitStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("IDCareer")
                        .HasColumnType("int");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalId")
                        .HasColumnType("int");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettlementResults")
                        .HasColumnType("int");

                    b.Property<string>("SettlementResultsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryStay")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkPermit")
                        .HasColumnType("int");

                    b.Property<string>("WorkPermitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveReason");

                    b.HasIndex("OriginalId");

                    b.ToTable("ArchivedEmployees", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Attach", b =>
                {
                    b.Property<int>("IDAttach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDAttach"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("Folder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IDAttach");

                    b.HasIndex("IDCompany");

                    b.ToTable("Attach", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Career", b =>
                {
                    b.Property<int>("IDCareer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCareer"));

                    b.Property<string>("CareerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<int>("IDCG")
                        .HasColumnType("int");

                    b.HasKey("IDCareer");

                    b.HasIndex("IDCG");

                    b.ToTable("Careers", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CareerGroup", b =>
                {
                    b.Property<int>("IDCG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCG"));

                    b.Property<string>("CareerGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCG");

                    b.ToTable("CareerGroups", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ColumnMappingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ColumnMappingTemplates", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Company", b =>
                {
                    b.Property<int>("IDCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCompany"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmountOfExemption")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionOfActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDField")
                        .HasColumnType("int");

                    b.Property<string>("LegalRepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPersonalities")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("QuantityNotYet")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationProfileIndex")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("TrackerID")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfBusiniess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDay")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCompany");

                    b.HasIndex("Delete_flag")
                        .HasDatabaseName("IX_Companies_DeleteFlag");

                    b.HasIndex("IDField")
                        .HasDatabaseName("IX_Companies_IDField");

                    b.HasIndex("TrackerID");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyAccommodationAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("CompanyId", "AccommodationId", "ValidFrom");

                    b.ToTable("CompanyAccommodationAgreements", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyLegalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegacyAttachId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoredFileId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyAttachId");

                    b.HasIndex("StoredFileId");

                    b.HasIndex("CompanyId", "TypeCode", "DocumentNumber");

                    b.ToTable("CompanyLegalDocuments", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyProfile", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnershipTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyRepresentatives", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.CompanySite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeUnitId");

                    b.HasIndex("CompanyId", "ValidFrom", "ValidTo");

                    b.ToTable("CompanySites", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.District", b =>
                {
                    b.Property<int>("IDDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDistrict"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("DisTrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDistrict");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.EconomicZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code", "ValidFrom")
                        .IsUnique();

                    b.ToTable("EconomicZones", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ElectronicIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentitySearchKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ForeignPersonId");

                    b.HasIndex("IdentitySearchKey");

                    b.ToTable("ElectronicIdentities", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Email", b =>
                {
                    b.Property<int>("IDEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEmail"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDEmail");

                    b.HasIndex("IDCompany");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Employee", b =>
                {
                    b.Property<int>("IDEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEmployee"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birthday");

                    b.Property<DateTime?>("CardCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateOfJoin")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfJoin");

                    b.Property<DateTime?>("DateOfLeave")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfLeave");

                    b.Property<int>("FamilyVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FamilyVisit");

                    b.Property<DateTime?>("FamilyVisitEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FamilyVisitEndDate");

                    b.Property<string>("FamilyVisitNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FamilyVisitNote");

                    b.Property<string>("FamilyVisitRelationship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FamilyVisitRelationship");

                    b.Property<string>("FamilyVisitRelativeIdCard")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FamilyVisitRelativeIdCard");

                    b.Property<string>("FamilyVisitRelativeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FamilyVisitRelativeName");

                    b.Property<DateTime?>("FamilyVisitStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FamilyVisitStartDate");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Hidden_flag")
                        .HasColumnType("int");

                    b.Property<int?>("IDCareer")
                        .HasColumnType("int");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettlementResults")
                        .HasColumnType("int");

                    b.Property<string>("SettlementResultsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryStay")
                        .HasColumnType("datetime2")
                        .HasColumnName("TemporaryStay");

                    b.Property<string>("VisaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkPermit")
                        .HasColumnType("int");

                    b.Property<string>("WorkPermitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingStatus")
                        .HasColumnType("int");

                    b.HasKey("IDEmployee");

                    b.HasIndex("FamilyVisit")
                        .HasDatabaseName("IX_Employees_FamilyVisit");

                    b.HasIndex("IDCareer");

                    b.HasIndex("IDCompany")
                        .HasDatabaseName("IX_Employees_IDCompany");

                    b.HasIndex("Nationality")
                        .HasDatabaseName("IX_Employees_Nationality");

                    b.HasIndex("TemporaryStay")
                        .HasDatabaseName("IX_Employees_TemporaryStay");

                    b.HasIndex("WorkingStatus", "Hidden_flag")
                        .HasDatabaseName("IX_Employees_WorkStatus");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.FamilyVisitDetail", b =>
                {
                    b.Property<int>("StayCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeNationalityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StayCaseId");

                    b.ToTable("FamilyVisitDetails", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Field", b =>
                {
                    b.Property<int>("IDField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDField"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDField");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ForeignPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDataIncomplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalityCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportSearchKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NationalityCode");

                    b.HasIndex("PassportSearchKey");

                    b.ToTable("ForeignPersons", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ForeignPersonSourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSynchronizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceFingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ForeignPersonId");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ForeignPersonSourceLinks", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ImmigrationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ForeignPersonId", "TypeCode", "ValidTo");

                    b.ToTable("ImmigrationDocuments", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ImportBackup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImportSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_ImportBackups_EntityTypeId");

                    b.ToTable("ImportBackups", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ImportHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedRows")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedRows")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ImportHistories", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanySiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectorNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("AdministrativeUnitId");

                    b.HasIndex("CompanySiteId");

                    b.HasIndex("InspectedAt");

                    b.ToTable("InspectionsV010", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.InspectionSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentsSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeCodeSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDescriptionSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.HasIndex("ForeignPersonId", "InspectionId")
                        .IsUnique();

                    b.ToTable("InspectionSubjects", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Investment", b =>
                {
                    b.Property<int>("IDInvestment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDInvestment"));

                    b.Property<decimal>("AmountOfMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDInvestment");

                    b.HasIndex("IDCompany");

                    b.ToTable("Investment", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.LegacyChangeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AfterXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode", "OccurredAt");

                    b.ToTable("LegacyChangeEvents", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.MigrationIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode", "SourceType");

                    b.ToTable("MigrationIssues", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.NationalityEntity", b =>
                {
                    b.Property<int>("IDNationality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNationality"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNationality");

                    b.ToTable("Nationality", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.PhoneNumber", b =>
                {
                    b.Property<int>("IDPhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPhoneNumber"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<int>("IDCompany")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPhoneNumber");

                    b.HasIndex("IDCompany");

                    b.ToTable("PhoneNumbers", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.ResidencePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<string>("ArrangementCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsibleCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("UnitLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("ForeignPersonId");

                    b.HasIndex("ResponsibleCompanyId");

                    b.HasIndex("AdministrativeUnitId", "ValidFrom", "ValidTo");

                    b.ToTable("ResidencePeriods", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.SchemaVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("SchemaVersions", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.SiteZoneMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanySiteId")
                        .HasColumnType("int");

                    b.Property<int>("EconomicZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EconomicZoneId");

                    b.HasIndex("CompanySiteId", "EconomicZoneId", "ValidFrom")
                        .IsUnique();

                    b.ToTable("SiteZoneMemberships", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.StayCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForeignPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SponsorCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("SponsorForeignPersonId")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SponsorCompanyId");

                    b.HasIndex("SponsorForeignPersonId");

                    b.HasIndex("ForeignPersonId", "ValidFrom", "ValidTo");

                    b.ToTable("StayCases", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.StoredFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.ToTable("StoredFiles", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Student", b =>
                {
                    b.Property<int>("IDStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStudent"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birthday");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<int>("EducationLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnrollmentDate");

                    b.Property<DateTime?>("ExpectedGraduation")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpectedGraduation");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Hidden_flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StudentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryStay")
                        .HasColumnType("datetime2")
                        .HasColumnName("TemporaryStay");

                    b.Property<DateTime?>("VisaExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("VisaExpiry");

                    b.Property<string>("VisaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDStudent");

                    b.HasIndex("Nationality")
                        .HasDatabaseName("IX_Students_Nationality");

                    b.HasIndex("VisaExpiry")
                        .HasDatabaseName("IX_Students_VisaExpiry");

                    b.HasIndex("Status", "Hidden_flag")
                        .HasDatabaseName("IX_Students_StatusHidden");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Ward", b =>
                {
                    b.Property<int>("IDWard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDWard"));

                    b.Property<int>("Delete_flag")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDWard");

                    b.ToTable("Wards", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.WebCredential", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("WebCredentials", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.WebRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeUnitId");

                    b.HasIndex("AccountId", "RoleCode", "AdministrativeUnitId")
                        .IsUnique()
                        .HasFilter("[AdministrativeUnitId] IS NOT NULL");

                    b.ToTable("WebRoleAssignments", (string)null);
                });

            modelBuilder.Entity("IRM.Data.Models.Accommodation", b =>
                {
                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany()
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdministrativeUnit");
                });

            modelBuilder.Entity("IRM.Data.Models.AdministrativeUnit", b =>
                {
                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("Predecessor");
                });

            modelBuilder.Entity("IRM.Data.Models.Attach", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany("Attachments")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.Career", b =>
                {
                    b.HasOne("IRM.Data.Models.CareerGroup", "CareerGroup")
                        .WithMany("Careers")
                        .HasForeignKey("IDCG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerGroup");
                });

            modelBuilder.Entity("IRM.Data.Models.Company", b =>
                {
                    b.HasOne("IRM.Data.Models.Field", "Field")
                        .WithMany("Companies")
                        .HasForeignKey("IDField")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Account", "Tracker")
                        .WithMany()
                        .HasForeignKey("TrackerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyAccommodationAgreement", b =>
                {
                    b.HasOne("IRM.Data.Models.Accommodation", "Accommodation")
                        .WithMany("CompanyAgreements")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyLegalDocument", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Attach", "LegacyAttach")
                        .WithMany()
                        .HasForeignKey("LegacyAttachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("LegacyAttach");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyProfile", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithOne()
                        .HasForeignKey("IRM.Data.Models.CompanyProfile", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanyRepresentative", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanySite", b =>
                {
                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany()
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeUnit");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.ElectronicIdentity", b =>
                {
                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany("ElectronicIdentities")
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForeignPerson");
                });

            modelBuilder.Entity("IRM.Data.Models.Email", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany("Emails")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.Employee", b =>
                {
                    b.HasOne("IRM.Data.Models.Career", "Career")
                        .WithMany()
                        .HasForeignKey("IDCareer");

                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.NationalityEntity", "NationalityNav")
                        .WithMany()
                        .HasForeignKey("Nationality")
                        .HasPrincipalKey("NationalityCode");

                    b.Navigation("Career");

                    b.Navigation("Company");

                    b.Navigation("NationalityNav");
                });

            modelBuilder.Entity("IRM.Data.Models.FamilyVisitDetail", b =>
                {
                    b.HasOne("IRM.Data.Models.StayCase", "StayCase")
                        .WithOne("FamilyVisitDetail")
                        .HasForeignKey("IRM.Data.Models.FamilyVisitDetail", "StayCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StayCase");
                });

            modelBuilder.Entity("IRM.Data.Models.ForeignPerson", b =>
                {
                    b.HasOne("IRM.Data.Models.NationalityEntity", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityCode")
                        .HasPrincipalKey("NationalityCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("IRM.Data.Models.ForeignPersonSourceLink", b =>
                {
                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany("SourceLinks")
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForeignPerson");
                });

            modelBuilder.Entity("IRM.Data.Models.ImmigrationDocument", b =>
                {
                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany("ImmigrationDocuments")
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForeignPerson");
                });

            modelBuilder.Entity("IRM.Data.Models.Inspection", b =>
                {
                    b.HasOne("IRM.Data.Models.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany()
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.CompanySite", "CompanySite")
                        .WithMany()
                        .HasForeignKey("CompanySiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Accommodation");

                    b.Navigation("AdministrativeUnit");

                    b.Navigation("CompanySite");
                });

            modelBuilder.Entity("IRM.Data.Models.InspectionSubject", b =>
                {
                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany()
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Inspection", "Inspection")
                        .WithMany("Subjects")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForeignPerson");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("IRM.Data.Models.Investment", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany("Investments")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.PhoneNumber", b =>
                {
                    b.HasOne("IRM.Data.Models.Company", "Company")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IRM.Data.Models.ResidencePeriod", b =>
                {
                    b.HasOne("IRM.Data.Models.Accommodation", "Accommodation")
                        .WithMany("ResidencePeriods")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany()
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany("ResidencePeriods")
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Company", "ResponsibleCompany")
                        .WithMany()
                        .HasForeignKey("ResponsibleCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Accommodation");

                    b.Navigation("AdministrativeUnit");

                    b.Navigation("ForeignPerson");

                    b.Navigation("ResponsibleCompany");
                });

            modelBuilder.Entity("IRM.Data.Models.SiteZoneMembership", b =>
                {
                    b.HasOne("IRM.Data.Models.CompanySite", "CompanySite")
                        .WithMany("ZoneMemberships")
                        .HasForeignKey("CompanySiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.EconomicZone", "EconomicZone")
                        .WithMany("SiteMemberships")
                        .HasForeignKey("EconomicZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySite");

                    b.Navigation("EconomicZone");
                });

            modelBuilder.Entity("IRM.Data.Models.StayCase", b =>
                {
                    b.HasOne("IRM.Data.Models.ForeignPerson", "ForeignPerson")
                        .WithMany("StayCases")
                        .HasForeignKey("ForeignPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.Company", "SponsorCompany")
                        .WithMany()
                        .HasForeignKey("SponsorCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRM.Data.Models.ForeignPerson", "SponsorForeignPerson")
                        .WithMany()
                        .HasForeignKey("SponsorForeignPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ForeignPerson");

                    b.Navigation("SponsorCompany");

                    b.Navigation("SponsorForeignPerson");
                });

            modelBuilder.Entity("IRM.Data.Models.Student", b =>
                {
                    b.HasOne("IRM.Data.Models.NationalityEntity", "NationalityNav")
                        .WithMany()
                        .HasForeignKey("Nationality")
                        .HasPrincipalKey("NationalityCode");

                    b.Navigation("NationalityNav");
                });

            modelBuilder.Entity("IRM.Data.Models.WebCredential", b =>
                {
                    b.HasOne("IRM.Data.Models.Account", "Account")
                        .WithOne()
                        .HasForeignKey("IRM.Data.Models.WebCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IRM.Data.Models.WebRoleAssignment", b =>
                {
                    b.HasOne("IRM.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRM.Data.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany()
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("AdministrativeUnit");
                });

            modelBuilder.Entity("IRM.Data.Models.Accommodation", b =>
                {
                    b.Navigation("CompanyAgreements");

                    b.Navigation("ResidencePeriods");
                });

            modelBuilder.Entity("IRM.Data.Models.CareerGroup", b =>
                {
                    b.Navigation("Careers");
                });

            modelBuilder.Entity("IRM.Data.Models.Company", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Emails");

                    b.Navigation("Employees");

                    b.Navigation("Investments");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("IRM.Data.Models.CompanySite", b =>
                {
                    b.Navigation("ZoneMemberships");
                });

            modelBuilder.Entity("IRM.Data.Models.EconomicZone", b =>
                {
                    b.Navigation("SiteMemberships");
                });

            modelBuilder.Entity("IRM.Data.Models.Field", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("IRM.Data.Models.ForeignPerson", b =>
                {
                    b.Navigation("ElectronicIdentities");

                    b.Navigation("ImmigrationDocuments");

                    b.Navigation("ResidencePeriods");

                    b.Navigation("SourceLinks");

                    b.Navigation("StayCases");
                });

            modelBuilder.Entity("IRM.Data.Models.Inspection", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("IRM.Data.Models.StayCase", b =>
                {
                    b.Navigation("FamilyVisitDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
